Source = Csv.Document(File.Contents("C:\Users\Taiyelolu\Documents\DA Mentorship with Daniel\LA_Crime_Data.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None])
#”Promote Headers” = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
#”Changes Type” = Table.TransformColumnTypes(#"Promoted Headers",{{"DR_NO", Int64.Type}, {"Date_Rptd", type date}, {"DATE_OCC", type date}, {"TIME_OCC", type time}, {"AREA_NAME", type text}, {"Crime", type text}, {"Vict_Age", Int64.Type}, {"Vict_Sex", type text}, {"Vict_Descent", type text}, {"Premise", type text}, {"Weapon", type text}, {"Status", type text}, {"LOCATION", type text}})
#”Replaced Value” = Table.ReplaceValue(#"Changed Type","M","Male",Replacer.ReplaceText,{"Vict_Sex"})
#”Replaced Value1” = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"Vict_Sex"})
#”Replaced Value2” = Table.ReplaceValue(#"Replaced Value1","X","Unknown",Replacer.ReplaceText,{"Vict_Sex"})
#”Replaced Value3” = Table.ReplaceValue(#"Replaced Value2","","Unknown",Replacer.ReplaceValue,{"Vict_Sex"})
#”Renamed Columns” = Table.RenameColumns(#"Replaced Value3",{{"Vict_Age", "Victim Age"}, {"Vict_Sex", "Victim Sex"}, {"Vict_Descent", "Victim Descent"}})
#”Replaced Value4” = Table.ReplaceValue(#"Renamed Columns","A","Other Asian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value5” = Table.ReplaceValue(#"Replaced Value4","B","Black",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value6” = Table.ReplaceValue(#"Replaced Value5","C","Chinese",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value7” = Table.ReplaceValue(#"Replaced Value6","D","Cambodian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value8” = Table.ReplaceValue(#"Replaced Value7","F","Filipino",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value9” = Table.ReplaceValue(#"Replaced Value8","G","Guamanian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value10” = Table.ReplaceValue(#"Replaced Value9","H","Hispanic/Latin/Mexican",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value11” = Table.ReplaceValue(#"Replaced Value10","I","American Indian/Alaskan Native",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value12” = Table.ReplaceValue(#"Replaced Value11","J","Japanese",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value13” = Table.ReplaceValue(#"Replaced Value12","K","Korean",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value14” = Table.ReplaceValue(#"Replaced Value13","L","Laotian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value15” = Table.ReplaceValue(#"Replaced Value14","O","Others",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value16” = Table.ReplaceValue(#"Replaced Value15","P","Pacific Islander",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value17” = Table.ReplaceValue(#"Replaced Value16","S","Samoan",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value18” = Table.ReplaceValue(#"Replaced Value17","U","Hawaiian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value19” = Table.ReplaceValue(#"Replaced Value18","V","Vietnamese",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value20” = Table.ReplaceValue(#"Replaced Value19","W","White",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value21” = Table.ReplaceValue(#"Replaced Value20","X","Unknown",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value22” = Table.ReplaceValue(#"Replaced Value21","Z","Asian Indian",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value23” = Table.ReplaceValue(#"Replaced Value22","","Unknown",Replacer.ReplaceValue,{"Victim Descent"})
#”Replaced Value24” = Table.ReplaceValue(#"Replaced Value23","","UNKNOWN",Replacer.ReplaceValue,{"Premise"})
#”Replaced Value25” = Table.ReplaceValue(#"Replaced Value24","","UNKNOWN",Replacer.ReplaceValue,{"Weapon"})
#”Capitalized Each Word” = Table.TransformColumns(#"Replaced Value25",{{"Crime", Text.Proper, type text}, {"Premise", Text.Proper, type text}, {"Weapon", Text.Proper, type text}, {"LOCATION", Text.Proper, type text}})
#”Inserted Hour” = Table.AddColumn(#"Capitalized Each Word", "Hour", each Time.Hour([TIME_OCC]), Int64.Type)
#”Reordered Columns” = Table.ReorderColumns(#"Inserted Hour",{"DR_NO", "Date_Rptd", "DATE_OCC", "TIME_OCC", "Hour", "AREA_NAME", "Crime", "Victim Age", "Victim Sex", "Victim Descent", "Premise", "Weapon", "Status", "LOCATION"})
#Renamed Columns1” = Table.RenameColumns(#"Reordered Columns",{{"DR_NO", "Dr_No"}, {"DATE_OCC", "Date_Occ"}, {"TIME_OCC", "Time_Occ"}, {"AREA_NAME", "Area_Name"}, {"LOCATION", "Location"}}) 
#”Replaced Value26” = Table.ReplaceValue(#"Renamed Columns1",-1,1,Replacer.ReplaceValue,{"Victim Age"})
#”Replaced Value27” = Table.ReplaceValue(#"Replaced Value26",-2,2,Replacer.ReplaceValue,{"Victim Age"})
#”Replaced Value28” = Table.ReplaceValue(#"Replaced Value27",-3,3,Replacer.ReplaceValue,{"Victim Age"})
#”Replaced Value29” = Table.ReplaceValue(#"Replaced Value28",-4,4,Replacer.ReplaceValue,{"Victim Age"})
#”Replaced Value30” =  Table.ReplaceValue(#"Replaced Value29","-","Unknown",Replacer.ReplaceText,{"Victim Sex"})
#”Replaced Value31” = Table.ReplaceValue(#"Replaced Value30","H","Unknown",Replacer.ReplaceText,{"Victim Sex"})
#”Replaced Value32” = Table.ReplaceValue(#"Replaced Value31","-","Unknown",Replacer.ReplaceText,{"Victim Descent"})
#”Replaced Value33” = Table.ReplaceValue(#"Replaced Value32","UNK","Unknown",Replacer.ReplaceText,{"Status"})
#”Replaced Value34” = Table.ReplaceValue(#"Replaced Value33","Invest Cont","Investigation Continues",Replacer.ReplaceText,{"Status"})
#”Replaced Value35” = Table.ReplaceValue(#"Replaced Value34","Juv Arrest","Juvenile Arrest",Replacer.ReplaceText,{"Status"})
#”Filtered Rows” = Table.SelectRows(#"Replaced Value35", each true)
#”Replaced Value36” = Table.ReplaceValue(#"Filtered Rows","Juv Other","Juvenile Other",Replacer.ReplaceText,{"Status"})
#”Removed Columns” = Table.RemoveColumns(#"Replaced Value36",{"Location"})

